### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AdamPalka** [ullenboom/jrtf#12]
When I generate Rtf document in Eclipse, everything works fine, but when I deploy my project to external Tomcat, I'm getting this error:

java.lang.NullPointerException
	at com.tutego.jrtf.RtfPara$2.rtf(RtfPara.java:129)
	at com.tutego.jrtf.RtfPara$6.rtf(RtfPara.java:320)
	at com.tutego.jrtf.Rtf.frameRtfParagraphWithEndingPar(Rtf.java:487)
	at com.tutego.jrtf.RtfSectionFormatAndHeaderFooter.headerForAllPages(RtfSectionFormatAndHeaderFooter.java:238)

Any ideas?

I'm using latest jRTF version, Tomcat 7.x, Eclipse Mars, JRE 1.7.

**Comment by AdamPalka** [comment]
Image not found. URL was null.
